/* Nexora-India customer account center. Logout remains header-only. */
(function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
  const app=()=>document.querySelector('#app');
  const user=()=>window.session?.user;
  let tabRequest=0;
  const tabs=[
    ['profile','👤','Profile'],['orders','📦','My Orders'],['addresses','📍','My Addresses'],['wishlist','❤️','Wishlist'],
    ['notifications','🔔','Notifications'],['payments','💳','Payments'],['security','🔒','Security'],['preferences','⚙️','Preferences'],
    ['support','🛟','Help & Support'],['privacy','🔐','Privacy']
  ];
  function client(){return window.sb?.from?window.sb:null}
  function nav(){return `<aside class="account-nav">${tabs.map((t,i)=>`<button type="button" class="${i===0?'active':''}" data-tab="${t[0]}">${t[1]} ${t[2]}</button>`).join('')}</aside>`}
  async function render(){
    if(!user()){location.hash='#/login';return}
    const root=app();if(!root)return;
    const request=++tabRequest;
    root.innerHTML=`<div class="account-page"><div class="account-hero"><span class="section-kicker">MY NEXORA</span><h1>My Account</h1><p>Manage your profile, orders, addresses, saved products, notifications and security.</p></div><div class="account-layout">${nav()}<section id="accountPanel"><div class="account-card"><div class="muted">Loading your account…</div></div></section></div></div>`;
    root.querySelectorAll('.account-nav button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
    await switchTab('profile',request);
  }
  async function switchTab(tab,parentRequest=tabRequest){
    if(!user()||parentRequest!==tabRequest)return;
    document.querySelectorAll('.account-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
    const panel=document.querySelector('#accountPanel');if(!panel)return;
    const request=++tabRequest;
    const f={profile:renderProfile,orders:renderOrders,addresses:renderAddresses,wishlist:renderWishlist,notifications:renderNotifications,payments:renderPayments,security:renderSecurity,preferences:renderPreferences,support:renderSupport,privacy:renderPrivacy}[tab];
    if(f)await f(panel,request);
  }
  async function getProfile(){const sb=client();if(!sb)throw new Error('Account database client is not ready.');const r=await sb.from('profiles').select('full_name,phone,address_line1,address_line2,city,state,pincode,date_of_birth,gender').eq('id',user().id).maybeSingle();if(r.error)throw r.error;return r.data||{}}
  async function renderProfile(panel,request){
    panel.innerHTML='<div class="account-card"><div class="muted">Loading profile…</div></div>';let p={},err='';try{p=await getProfile()}catch(e){err=e.message}
    if(request!==tabRequest||!user())return;const m=user().user_metadata||{};
    panel.innerHTML=`<div class="account-card"><h2>Profile details</h2>${err?`<div class="notice error">Profile could not be loaded. You can still edit and save. ${esc(err)}</div>`:''}<div class="account-grid"><div class="field"><label>Email</label><input class="input" value="${esc(user().email)}" disabled></div><div class="field"><label>Mobile</label><input id="acPhone" class="input" value="${esc(p.phone||m.phone||'')}"></div><div class="field"><label>Full name</label><input id="acName" class="input" value="${esc(p.full_name||m.full_name||'')}"></div><div class="field"><label>Date of birth</label><input id="acDob" class="input" type="date" value="${esc(p.date_of_birth||'')}"></div><div class="field"><label>Gender</label><select id="acGender" class="input"><option value="">Prefer not to say</option><option ${p.gender==='Male'?'selected':''}>Male</option><option ${p.gender==='Female'?'selected':''}>Female</option><option ${p.gender==='Other'?'selected':''}>Other</option></select></div><div class="field full"><label>Address line 1</label><input id="acAddress1" class="input" value="${esc(p.address_line1||'')}"></div><div class="field full"><label>Address line 2</label><input id="acAddress2" class="input" value="${esc(p.address_line2||'')}"></div><div class="field"><label>City</label><input id="acCity" class="input" value="${esc(p.city||'')}"></div><div class="field"><label>State</label><input id="acState" class="input" value="${esc(p.state||'')}"></div><div class="field"><label>Pincode</label><input id="acPincode" class="input" inputmode="numeric" value="${esc(p.pincode||'')}"></div></div><div class="account-actions"><button type="button" id="saveAccount" class="btn">Save changes</button></div><div id="accountMsg"></div></div>`;
    document.querySelector('#saveAccount')?.addEventListener('click',saveProfile);
  }
  async function saveProfile(){const b=document.querySelector('#saveAccount'),sb=client(),msg=document.querySelector('#accountMsg');if(!b||!user()||!sb)return;b.disabled=true;b.textContent='Saving…';const payload={full_name:document.querySelector('#acName').value.trim(),phone:document.querySelector('#acPhone').value.trim(),address_line1:document.querySelector('#acAddress1').value.trim(),address_line2:document.querySelector('#acAddress2').value.trim(),city:document.querySelector('#acCity').value.trim(),state:document.querySelector('#acState').value.trim(),pincode:document.querySelector('#acPincode').value.trim(),date_of_birth:document.querySelector('#acDob').value||null,gender:document.querySelector('#acGender').value||null};try{let r=await sb.from('profiles').update(payload).eq('id',user().id).select().maybeSingle();if(r.error)throw r.error;if(!r.data){const up=await sb.from('profiles').upsert({id:user().id,...payload},{onConflict:'id'});if(up.error)throw up.error}if(msg)msg.innerHTML='<div class="notice success">Profile updated successfully.</div>'}catch(e){if(msg)msg.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}finally{b.disabled=false;b.textContent='Save changes'}}
  async function renderOrders(panel,request){panel.innerHTML='<div class="account-card"><div class="muted">Loading orders…</div></div>';try{const sb=client();if(!sb)throw new Error('Account database client is not ready.');const r=await sb.from('orders').select('id,order_number,created_at,total_amount,order_status,payment_status,shipping_status,tracking_number,tracking_url,carrier,order_items(product_name,quantity,unit_selling_price)').eq('user_id',user().id).order('created_at',{ascending:false});if(r.error)throw r.error;if(request!==tabRequest)return;const orders=r.data||[];panel.innerHTML=`<div class="account-card"><h2>My Orders</h2>${orders.length?orders.map(o=>`<article class="account-order"><div class="account-order-head"><div><b>${esc(o.order_number||o.id)}</b><div class="muted">${new Date(o.created_at).toLocaleDateString('en-IN')}</div></div><span class="badge">${esc(o.order_status)}</span></div><div class="account-order-items">${(o.order_items||[]).map(i=>`${esc(i.product_name)} × ${i.quantity} — ${money(Number(i.unit_selling_price)*Number(i.quantity))}`).join('<br>')}</div><div class="account-actions"><b>Total ${money(o.total_amount)}</b><span class="muted">Payment: ${esc(o.payment_status)}</span><span class="muted">Shipping: ${esc(o.shipping_status)}</span>${o.tracking_url?`<a class="btn secondary" target="_blank" rel="noopener" href="${esc(o.tracking_url)}">Track shipment</a>`:''}</div></article>`).join(''):'<div class="account-empty">You have no orders yet.<br><a class="btn" href="#/products" style="margin-top:12px">Start shopping</a></div>'}</div>`}catch(e){if(request===tabRequest)panel.innerHTML=`<div class="account-card"><h2>My Orders</h2><div class="notice error">Could not load orders: ${esc(e.message)}</div></div>`}}
  async function renderAddresses(panel,request){panel.innerHTML='<div class="account-card"><div class="muted">Loading addresses…</div></div>';try{const sb=client(),r=await sb.from('addresses').select('*').eq('user_id',user().id).order('is_default',{ascending:false}).order('created_at',{ascending:false});if(r.error)throw r.error;if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><div class="between"><h2>My Addresses</h2><button class="btn" id="addAddress">Add address</button></div><div id="addressList">${(r.data||[]).map(a=>`<article class="account-order"><div class="between"><b>${esc(a.name)} ${a.is_default?'<span class="badge">Default</span>':''}</b><span>${esc(a.phone)}</span></div><p>${esc(a.address_line1)}${a.address_line2?', '+esc(a.address_line2):''}, ${esc(a.city)}, ${esc(a.state)} - ${esc(a.pincode)}</p><div class="account-actions"><button class="btn secondary" data-default="${a.id}">Set default</button><button class="btn secondary" data-delete-address="${a.id}">Delete</button></div></article>`).join('')||'<div class="account-empty">No saved addresses yet.</div>'}</div><div id="addressForm"></div></div>`;document.querySelector('#addAddress').onclick=()=>addressForm();panel.querySelectorAll('[data-default]').forEach(b=>b.onclick=()=>setDefaultAddress(b.dataset.default));panel.querySelectorAll('[data-delete-address]').forEach(b=>b.onclick=()=>deleteAddress(b.dataset.deleteAddress))}catch(e){panel.innerHTML=`<div class="account-card"><div class="notice error">Could not load addresses: ${esc(e.message)}</div></div>`}}
  function addressForm(){const f=document.querySelector('#addressForm');if(!f)return;f.innerHTML=`<div class="subcard"><h3>Add address</h3><div class="account-grid"><input id="adName" class="input" placeholder="Name"><input id="adPhone" class="input" placeholder="Mobile"><input id="ad1" class="input full" placeholder="Address line 1"><input id="ad2" class="input full" placeholder="Address line 2"><input id="adCity" class="input" placeholder="City"><input id="adState" class="input" placeholder="State"><input id="adPin" class="input" placeholder="Pincode"><input id="adLandmark" class="input" placeholder="Landmark"></div><label><input id="adDefault" type="checkbox"> Make default</label><div class="account-actions"><button class="btn" id="saveAddress">Save address</button></div><div id="addressMsg"></div></div>`;document.querySelector('#saveAddress').onclick=saveAddress}
  async function saveAddress(){const sb=client(),m=document.querySelector('#addressMsg');try{const p={user_id:user().id,name:document.querySelector('#adName').value.trim(),phone:document.querySelector('#adPhone').value.trim(),address_line1:document.querySelector('#ad1').value.trim(),address_line2:document.querySelector('#ad2').value.trim()||null,city:document.querySelector('#adCity').value.trim(),state:document.querySelector('#adState').value.trim(),pincode:document.querySelector('#adPin').value.trim(),landmark:document.querySelector('#adLandmark').value.trim()||null,is_default:document.querySelector('#adDefault').checked};if(!p.name||!p.phone||!p.address_line1||!p.city||!p.state||!p.pincode)throw new Error('Please fill all required address fields.');if(p.is_default)await sb.from('addresses').update({is_default:false}).eq('user_id',user().id);const r=await sb.from('addresses').insert(p);if(r.error)throw r.error;await renderAddresses(document.querySelector('#accountPanel'),++tabRequest)}catch(e){if(m)m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}}
  async function setDefaultAddress(id){const sb=client();await sb.from('addresses').update({is_default:false}).eq('user_id',user().id);await sb.from('addresses').update({is_default:true}).eq('id',id).eq('user_id',user().id);await renderAddresses(document.querySelector('#accountPanel'),++tabRequest)}
  async function deleteAddress(id){if(!confirm('Delete this address?'))return;const r=await client().from('addresses').delete().eq('id',id).eq('user_id',user().id);if(r.error)alert(r.error.message);await renderAddresses(document.querySelector('#accountPanel'),++tabRequest)}
  async function renderWishlist(panel,request){try{const sb=client();const r=await sb.from('wishlists').select('id,product_id,created_at,products(id,name,image_url,selling_price,stock)').eq('user_id',user().id).order('created_at',{ascending:false});if(r.error)throw r.error;if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><h2>Wishlist</h2>${(r.data||[]).map(w=>`<article class="account-order"><div class="between"><div><b>${esc(w.products?.name||'Product')}</b><div class="muted">${money(w.products?.selling_price)}</div></div><button class="btn secondary" data-remove-wish="${w.id}">Remove</button></div><div class="account-actions"><button class="btn" data-add-wish="${w.product_id}" ${w.products?.stock>0?'':'disabled'}>Add to cart</button></div></article>`).join('')||'<div class="account-empty">Your wishlist is empty.</div>'}</div>`;panel.querySelectorAll('[data-remove-wish]').forEach(b=>b.onclick=async()=>{await sb.from('wishlists').delete().eq('id',b.dataset.removeWish).eq('user_id',user().id);renderWishlist(panel,++tabRequest)});panel.querySelectorAll('[data-add-wish]').forEach(b=>b.onclick=()=>window.addCart?.(b.dataset.addWish))}catch(e){panel.innerHTML=`<div class="account-card"><div class="notice error">Could not load wishlist: ${esc(e.message)}</div></div>`}}
  async function renderNotifications(panel,request){const sb=client();try{const r=await sb.from('notifications').select('id,type,title,message,is_read,created_at').eq('user_id',user().id).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><div class="between"><h2>Notifications</h2><button class="btn secondary" id="markRead">Mark all read</button></div>${(r.data||[]).map(n=>`<article class="account-order"><b>${esc(n.title)}</b><div>${esc(n.message)}</div><small class="muted">${new Date(n.created_at).toLocaleString('en-IN')}</small>${!n.is_read?`<button class="btn secondary" data-read="${n.id}">Mark read</button>`:''}</article>`).join('')||'<div class="account-empty">No notifications.</div>'}</div>`;panel.querySelector('#markRead').onclick=async()=>{await sb.from('notifications').update({is_read:true}).eq('user_id',user().id);renderNotifications(panel,++tabRequest)};panel.querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{await sb.from('notifications').update({is_read:true}).eq('id',b.dataset.read).eq('user_id',user().id);renderNotifications(panel,++tabRequest)})}catch(e){panel.innerHTML=`<div class="account-card"><div class="notice error">Could not load notifications: ${esc(e.message)}</div></div>`}}
  async function renderPayments(panel,request){const sb=client();try{const r=await sb.from('payment_records').select('id,order_id,method,amount,utr,status,submitted_at,verified_at,created_at').in('order_id',(await sb.from('orders').select('id').eq('user_id',user().id)).data?.map(x=>x.id)||[]).order('created_at',{ascending:false});if(r.error)throw r.error;if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><h2>Payments</h2><p class="muted">For security, Nexora-India does not store card numbers. This section shows your payment history.</p>${(r.data||[]).map(p=>`<article class="account-order"><div class="between"><b>${esc(p.method)}</b><span class="badge">${esc(p.status)}</span></div><p>${money(p.amount)}${p.utr?' · UTR '+esc(p.utr):''}</p><small class="muted">${new Date(p.created_at).toLocaleString('en-IN')}</small></article>`).join('')||'<div class="account-empty">No payment records yet.</div>'}</div>`}catch(e){panel.innerHTML=`<div class="account-card"><div class="notice error">Could not load payment history: ${esc(e.message)}</div></div>`}}
  async function renderSecurity(panel,request){if(request!==tabRequest)return;let factors=[];try{const r=await client().auth.mfa.listFactors();factors=r.data?.totp||[]}catch{}const verified=factors.filter(f=>f.status==='verified');panel.innerHTML=`<div class="account-card"><h2>Security</h2><div class="security-list"><div class="security-row"><div><b>Change Password</b><p class="muted">Change your password while signed in.</p></div><button class="btn secondary" id="changePassword">Change</button></div><div class="security-row"><div><b>Password Recovery</b><p class="muted">Send a password reset link to your email.</p></div><a class="btn secondary" href="#/forgot">Reset</a></div><div class="security-row"><div><b>Email Verification</b><p class="muted">${user().email_confirmed_at?'Your email is verified.':'Your email is not verified.'}</p></div></div><div class="security-row"><div><b>Two-Factor Authentication</b><p class="muted">${verified.length?'2FA is enabled on this account.':'Add an authenticator app for stronger login protection.'}</p></div><button class="btn secondary" id="mfaAction">${verified.length?'Disable':'Enable'}</button></div><div class="security-row"><div><b>Other Sessions</b><p class="muted">Sign out other active sessions for this account.</p></div><button class="btn secondary" id="signOther">Sign out other devices</button></div></div><div id="securityMsg"></div><div id="mfaArea"></div><h3>Recent security activity</h3><div id="securityEvents" class="account-order">Loading…</div></div>`;
    document.querySelector('#changePassword').onclick=changePassword;document.querySelector('#signOther').onclick=signOtherSessions;document.querySelector('#mfaAction').onclick=()=>verified.length?disableMfa(verified[0].id):startMfa();loadSecurityEvents();}
  async function changePassword(){const p=prompt('Enter your new password (minimum 8 characters):');if(!p||p.length<8)return alert('Password must be at least 8 characters.');const r=await client().auth.updateUser({password:p});alert(r.error?r.error.message:'Password changed successfully.')}
  async function signOtherSessions(){const r=await client().auth.signOut({scope:'others'});document.querySelector('#securityMsg').innerHTML=r.error?`<div class="notice error">${esc(r.error.message)}</div>`:'<div class="notice success">Other sessions have been signed out.</div>'}
  async function startMfa(){const area=document.querySelector('#mfaArea');try{const r=await client().auth.mfa.enroll({factorType:'totp',friendlyName:'Nexora Authenticator'});if(r.error)throw r.error;area.innerHTML=`<div class="subcard"><h3>Set up 2FA</h3><p>Scan this QR code with an authenticator app, then enter the 6-digit code.</p><img alt="2FA QR code" src="${esc(r.data.totp.qr_code)}" style="max-width:220px"><input id="mfaCode" class="input" inputmode="numeric" maxlength="6" placeholder="6-digit code"><button class="btn" id="verifyMfa">Verify & enable</button></div>`;document.querySelector('#verifyMfa').onclick=async()=>{const ch=await client().auth.mfa.challenge({factorId:r.data.id});if(ch.error)return alert(ch.error.message);const v=await client().auth.mfa.verify({factorId:r.data.id,challengeId:ch.data.id,code:document.querySelector('#mfaCode').value.trim()});if(v.error)alert(v.error.message);else renderSecurity(document.querySelector('#accountPanel'),++tabRequest)}}catch(e){area.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}}
  async function disableMfa(id){if(!confirm('Disable two-factor authentication?'))return;const r=await client().auth.mfa.unenroll({factorId:id});if(r.error)alert(r.error.message);else renderSecurity(document.querySelector('#accountPanel'),++tabRequest)}
  async function loadSecurityEvents(){const el=document.querySelector('#securityEvents');try{const r=await client().from('security_events').select('event_type,created_at,metadata').eq('user_id',user().id).order('created_at',{ascending:false}).limit(20);if(r.error)throw r.error;el.innerHTML=(r.data||[]).map(x=>`<div class="between"><span>${esc(x.event_type)}</span><small>${new Date(x.created_at).toLocaleString('en-IN')}</small></div>`).join('')||'No recent security events.'}catch(e){el.textContent='Security activity is not available right now.'}}
  async function renderPreferences(panel,request){const sb=client();let p={};try{const r=await sb.from('user_preferences').select('*').eq('user_id',user().id).maybeSingle();if(r.data)p=r.data}catch{}if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><h2>Preferences</h2><div class="field"><label>Language</label><select id="prefLang" class="input"><option ${p.language==='English'||!p.language?'selected':''}>English</option><option ${p.language==='Hindi'?'selected':''}>Hindi</option></select></div><div class="field"><label>Currency</label><select id="prefCurrency" class="input"><option selected>INR</option></select></div>${[['email_notifications','Email notifications'],['sms_notifications','SMS notifications'],['marketing_notifications','Offers and marketing']].map(x=>`<label class="toggle-row"><input id="${x[0]}" type="checkbox" ${p[x[0]]!==false?'checked':''}> ${x[1]}</label>`).join('')}<button class="btn" id="savePrefs">Save preferences</button><div id="prefMsg"></div></div>`;document.querySelector('#savePrefs').onclick=async()=>{const payload={user_id:user().id,language:document.querySelector('#prefLang').value,currency:document.querySelector('#prefCurrency').value,email_notifications:document.querySelector('#email_notifications').checked,sms_notifications:document.querySelector('#sms_notifications').checked,marketing_notifications:document.querySelector('#marketing_notifications').checked,updated_at:new Date().toISOString()};const r=await sb.from('user_preferences').upsert(payload,{onConflict:'user_id'});document.querySelector('#prefMsg').innerHTML=r.error?`<div class="notice error">${esc(r.error.message)}</div>`:'<div class="notice success">Preferences saved.</div>'}}
  async function renderSupport(panel,request){const sb=client();const r=await sb.from('support_tickets').select('id,subject,message,status,created_at').eq('user_id',user().id).order('created_at',{ascending:false});if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><div class="between"><h2>Help & Support</h2><button class="btn" id="newTicket">Contact support</button></div><p class="muted">Create a support request and track its status here.</p>${r.error?`<div class="notice error">${esc(r.error.message)}</div>`:(r.data||[]).map(t=>`<article class="account-order"><div class="between"><b>${esc(t.subject)}</b><span class="badge">${esc(t.status)}</span></div><p>${esc(t.message)}</p><small class="muted">${new Date(t.created_at).toLocaleString('en-IN')}</small></article>`).join('')||'<div class="account-empty">No support requests.</div>'}<div id="ticketForm"></div></div>`;document.querySelector('#newTicket').onclick=()=>{document.querySelector('#ticketForm').innerHTML='<div class="subcard"><input id="ticketSubject" class="input" placeholder="Subject"><textarea id="ticketMessage" class="input" placeholder="How can we help?"></textarea><button class="btn" id="sendTicket">Submit request</button><div id="ticketMsg"></div></div>';document.querySelector('#sendTicket').onclick=async()=>{const x=await sb.from('support_tickets').insert({user_id:user().id,subject:document.querySelector('#ticketSubject').value.trim(),message:document.querySelector('#ticketMessage').value.trim()});document.querySelector('#ticketMsg').innerHTML=x.error?`<div class="notice error">${esc(x.error.message)}</div>`:'<div class="notice success">Support request submitted.</div>'}}}
  async function renderPrivacy(panel,request){const sb=client();let d=null;try{d=(await sb.from('account_deletion_requests').select('*').eq('user_id',user().id).maybeSingle()).data}catch{}if(request!==tabRequest)return;panel.innerHTML=`<div class="account-card"><h2>Privacy & Data</h2><div class="security-list"><div class="security-row"><div><b>Account data</b><p class="muted">Your profile, order and support data are associated with your account.</p></div></div><div class="security-row"><div><b>Request account deletion</b><p class="muted">Submit a deletion request. Your account will not be deleted automatically from this screen.</p></div><button class="btn secondary" id="deleteRequest">${d?.status==='pending'?'Request pending':'Request deletion'}</button></div></div><div id="privacyMsg"></div></div>`;document.querySelector('#deleteRequest').onclick=async()=>{if(d?.status==='pending')return;const reason=prompt('Optional reason for deleting your account:')||null;const r=await sb.from('account_deletion_requests').upsert({user_id:user().id,reason,status:'pending'},{onConflict:'user_id'});document.querySelector('#privacyMsg').innerHTML=r.error?`<div class="notice error">${esc(r.error.message)}</div>`:'<div class="notice success">Deletion request submitted. Support will review it.</div>'}}
  const oldRoute=window.route;window.route=function(){if(location.hash==='#/account'){render();return}return oldRoute&&oldRoute()};
})();
