/* Nexora-India Point 8: admin dashboard shell. */
(function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function render(){
  if(!window.session){location.hash='#/login';return}
  const app=document.querySelector('#app');
  app.innerHTML='<div class="admin-page"><div class="admin-head"><div><span class="section-kicker">ADMIN CONTROL</span><h1>Admin Dashboard</h1></div><button id="adminRefresh" class="btn">Refresh</button></div><div class="admin-grid"><div class="admin-stat"><span>Products</span><strong id="asProducts">—</strong></div><div class="admin-stat"><span>Customers</span><strong id="asCustomers">—</strong></div><div class="admin-stat"><span>Orders</span><strong id="asOrders">—</strong></div><div class="admin-stat"><span>Offers</span><strong id="asOffers">—</strong></div></div><div class="admin-tabs"><button class="active" data-tab="overview">Overview</button><button data-tab="products">Products</button><button data-tab="orders">Orders</button><button data-tab="customers">Customers</button><button data-tab="offers">Offers</button><button data-tab="categories">Categories</button><button data-tab="sync">Sync</button></div><section id="adminPanel" class="admin-card"></section></div>';
  document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelector('#adminRefresh').onclick=()=>tab('overview');await tab('overview');
 }
 async function count(table){const r=await window.sb.from(table).select('id',{count:'exact',head:true});return r.count||0}
 async function tab(t){document.querySelectorAll('.admin-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));const p=document.querySelector('#adminPanel');if(t==='overview'){const [a,b,c,d]=await Promise.all([count('products'),count('profiles'),count('orders'),count('offers')]);['asProducts','asCustomers','asOrders','asOffers'].forEach((id,i)=>document.getElementById(id).textContent=[a,b,c,d][i]);p.innerHTML='<h2>Overview</h2><p class="muted">Use the sections above to manage the store. Category management and offer controls are available here.</p>';return}if(t==='products'){p.innerHTML='<h2>Products</h2><p class="muted">Product management UI will be expanded in the dedicated product controls phase.</p>';return}if(t==='orders'){p.innerHTML='<h2>Orders</h2><p class="muted">Review orders through the existing authenticated order APIs.</p>';return}if(t==='customers'){p.innerHTML='<h2>Customers</h2><p class="muted">Customer profiles are protected by row-level security.</p>';return}if(t==='offers'){p.innerHTML='<h2>Offers</h2><p class="muted">Offer management UI is prepared for the offer system.</p>';return}if(t==='categories'){p.innerHTML='<h2>Categories</h2><p class="muted">Dynamic category management UI is handled in Point 9.</p>';return}p.innerHTML='<h2>Supplier Sync</h2><p class="muted">CJ and DeoDap sync controls remain connected to the existing backend.</p>'}
 const old=window.route;window.route=function(){if(location.hash==='#/admin'){render();return}return old&&old()};
})();