/* Nexora-India Point 9: dynamic category management. */
(function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const sb=()=>window.sb;
 async function renderCategories(p){
  const {data,error}=await sb().from('categories').select('id,name,slug,description,icon_url,banner_url,seo_title,seo_description,category_type,source_name,active,sort_order').order('sort_order').order('name');
  if(error){p.innerHTML=`<div class="notice error">${esc(error.message)}</div>`;return}
  p.innerHTML=`<h2>Dynamic Categories</h2><p class="muted">Create, edit, reorder and publish categories directly from Admin. No code change is required for a new category.</p><div class="admin-form"><div class="field"><label>Name</label><input id="catName" class="input"></div><div class="field"><label>Slug</label><input id="catSlug" class="input" placeholder="auto-generated if blank"></div><div class="field"><label>Category type</label><select id="catType" class="input"><option value="OWN">OWN</option><option value="SUPPLIER">SUPPLIER</option></select></div><div class="field"><label>Source name</label><input id="catSource" class="input" placeholder="e.g. CJ / DeoDap / OWN"></div><div class="field"><label>Sort order</label><input id="catOrder" class="input" type="number" value="0"></div><div class="field"><label>Icon URL</label><input id="catIcon" class="input"></div><div class="field full"><label>Banner URL</label><input id="catBanner" class="input"></div><div class="field full"><label>Description</label><textarea id="catDesc" class="input" rows="2"></textarea></div><div class="field"><label>SEO title</label><input id="catSeoTitle" class="input"></div><div class="field"><label>SEO description</label><input id="catSeoDesc" class="input"></div></div><div class="admin-actions"><button id="catCreate" class="btn">Create Category</button><button id="catReset" class="btn secondary">Reset</button></div><div id="catMsg"></div><hr><div class="table-scroll"><table class="admin-table"><thead><tr><th>Category</th><th>Type</th><th>Source</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>${(data||[]).map(c=>`<tr><td><b>${esc(c.name)}</b><br><span class="muted">${esc(c.slug)}</span></td><td>${esc(c.category_type||'OWN')}</td><td>${esc(c.source_name||'OWN')}</td><td><input class="input" data-order="${c.id}" value="${Number(c.sort_order)||0}" type="number"></td><td>${c.active?'Active':'Hidden'}</td><td><button class="btn small" data-cat-save="${c.id}">Save order</button> <button class="btn small secondary" data-cat-toggle="${c.id}" data-value="${c.active}">${c.active?'Hide':'Publish'}</button></td></tr>`).join('')}</tbody></table></div>`;
  const msg=(t,type='success')=>document.querySelector('#catMsg').innerHTML=`<div class="notice ${type}">${esc(t)}</div>`;
  const reset=()=>['catName','catSlug','catSource','catOrder','catIcon','catBanner','catDesc','catSeoTitle','catSeoDesc'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=id==='catOrder'?'0':''});reset();
  document.querySelector('#catCreate').onclick=async()=>{const name=document.querySelector('#catName').value.trim();if(!name)return msg('Category name is required.','error');const slug=(document.querySelector('#catSlug').value.trim()||name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));const payload={name,slug,category_type:document.querySelector('#catType').value,source_name:document.querySelector('#catSource').value.trim()||'OWN',sort_order:Number(document.querySelector('#catOrder').value)||0,icon_url:document.querySelector('#catIcon').value.trim()||null,banner_url:document.querySelector('#catBanner').value.trim()||null,description:document.querySelector('#catDesc').value.trim()||null,seo_title:document.querySelector('#catSeoTitle').value.trim()||null,seo_description:document.querySelector('#catSeoDesc').value.trim()||null,active:true};const r=await sb().from('categories').insert(payload);if(r.error)return msg(r.error.message,'error');await renderCategories(p)};
  document.querySelector('#catReset').onclick=reset;
  document.querySelectorAll('[data-cat-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.catSave;const order=Number(document.querySelector(`[data-order="${id}"]`).value)||0;const r=await sb().from('categories').update({sort_order:order}).eq('id',id);r.error?msg(r.error.message,'error'):renderCategories(p)});
  document.querySelectorAll('[data-cat-toggle]').forEach(b=>b.onclick=async()=>{const r=await sb().from('categories').update({active:b.dataset.value!=='true'}).eq('id',b.dataset.catToggle);r.error?msg(r.error.message,'error'):renderCategories(p)});
 }
 const old=window.route;window.route=function(){if(location.hash==='#/admin'){setTimeout(()=>{const buttons=document.querySelectorAll('.admin-tabs button');const target=[...buttons].find(b=>b.dataset.tab==='categories');if(target&&!target.dataset.categoryBound){target.dataset.categoryBound='1';target.onclick=()=>{buttons.forEach(x=>x.classList.toggle('active',x===target));renderCategories(document.querySelector('#adminPanel'))}}},0);return old&&old()};
})();