/* Nexora-India Point 5: checkout UX. */
(function(){
 const esc=window.esc||((v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])));
 const money=window.money||((n)=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2}));
 const ps=()=>window.products||[];
 const minQty=p=>Math.max(1,Number(p?.electrical_min_order_qty??p?.min_order_qty??1));
 const delivery=p=>Number(p?.electrical_delivery_charge??p?.delivery_charge??0);
 function rows(){return (window.cart||[]).map(i=>{const p=ps().find(x=>x.id===i.id);return p?{...i,p}:null}).filter(Boolean)}
 function totals(){const r=rows();let subtotal=0,shipping=0;r.forEach(x=>{subtotal+=Number(x.p.selling_price||0)*x.qty;shipping+=delivery(x.p)*x.qty});return {r,subtotal,shipping,total:subtotal+shipping}}
 async function render(){
  if(!window.session){location.hash='#/login';return}
  const t=totals();
  if(!t.r.length){document.querySelector('#app').innerHTML='<div class="container"><div class="panel"><h2>Your cart is empty</h2><a class="btn" href="#/products">Browse products</a></div></div>';return}
  document.querySelector('#app').innerHTML=`<div class="checkout-page"><div class="checkout-head"><span class="section-kicker">SECURE CHECKOUT</span><h1>Complete your order</h1><p>Review your details and payment before placing the order.</p></div><div class="checkout-layout"><section class="checkout-form"><div class="checkout-card"><h2>Delivery details</h2><div class="checkout-grid"><div class="field"><label>Full name</label><input id="coName" class="input" autocomplete="name"></div><div class="field"><label>Mobile number</label><input id="coPhone" class="input" inputmode="tel" autocomplete="tel"></div><div class="field full"><label>Address</label><textarea id="coAddress" class="input" rows="3" autocomplete="street-address"></textarea></div><div class="field"><label>City</label><input id="coCity" class="input"></div><div class="field"><label>State</label><input id="coState" class="input"></div><div class="field"><label>Pincode</label><input id="coPin" class="input" inputmode="numeric" maxlength="6"></div><div class="field full"><label>Landmark (optional)</label><input id="coLandmark" class="input"></div></div></div><div class="checkout-card"><h2>Payment</h2><div class="payment-method"><b>UPI</b><span>Pay using your UPI app, then enter the UTR/reference number.</span></div><div class="field"><label>UPI UTR / Reference <span class="muted">(optional now)</span></label><input id="coUtr" class="input" maxlength="80"></div><div class="notice">Without a UTR, the order remains pending payment. You can submit the UTR later from My Orders.</div></div><button id="placeOrder" class="btn checkout-submit">Place order</button><div id="checkoutMsg"></div></section><aside class="checkout-summary"><h2>Order summary</h2>${t.r.map(x=>`<div class="summary-item"><div><b>${esc(x.p.name)}</b><span>Qty ${x.qty}</span></div><strong>${money(Number(x.p.selling_price)*x.qty)}</strong></div>`).join('')}<hr><div class="summary-line"><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div class="summary-line"><span>Delivery</span><b>${t.shipping?money(t.shipping):'Free'}</b></div><div class="summary-total"><span>Total</span><strong>${money(t.total)}</strong></div></aside></div></div>`;
  document.querySelector('#placeOrder').onclick=submit;
 }
 function msg(text,type='error'){const e=document.querySelector('#checkoutMsg');if(e)e.innerHTML=`<div class="notice ${type}">${esc(text)}</div>`}
 async function submit(){
  const b=document.querySelector('#placeOrder');b.disabled=true;b.textContent='Placing order…';
  try{const t=totals(),name=$('#coName').value.trim(),phone=$('#coPhone').value.trim(),address=$('#coAddress').value.trim(),city=$('#coCity').value.trim(),state=$('#coState').value.trim(),pincode=$('#coPin').value.trim(),utr=$('#coUtr').value.trim();if(!name||!phone||!address||!city||!state||!/^[0-9]{6}$/.test(pincode))throw new Error('Please complete all required delivery details and enter a valid 6-digit pincode.');const r=await fetch('/api/order',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${window.session.access_token}`},body:JSON.stringify({items:t.r.map(x=>({product_id:x.id,quantity:x.qty})),customer:{name,phone,address_line1:address,city,state,pincode,landmark:$('#coLandmark').value.trim()},utr:utr||null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to place order');window.cart=[];localStorage.removeItem('nexora_cart');window.updateCartCount?.();msg(`Order ${d.order_number} created successfully. Total ${money(d.total_amount)}.`,'success');b.remove();setTimeout(()=>location.hash='#/orders',900)}catch(e){msg(e.message);b.disabled=false;b.textContent='Place order'}}
 function route(){if(location.hash==='#/checkout'){render();return true}return false}const old=window.route;window.route=function(){if(route())return;return old&&old()};window.addEventListener('hashchange',route);
})();
