(()=>{'use strict';
if(window.__nexoraCheckoutHotfix)return;window.__nexoraCheckoutHotfix=true;window.__nexoraOfferCode='';window.__nexoraOfferDiscount=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const originalFetch=window.fetch;window.fetch=async(input,init={})=>{try{const url=typeof input==='string'?input:input?.url||'';if(url.endsWith('/api/order')&&init?.body&&window.__nexoraOfferCode){const body=JSON.parse(init.body);body.offer_code=window.__nexoraOfferCode;init={...init,body:JSON.stringify(body)}}}catch{}return originalFetch(input,init)};
async function setup(){if(!location.hash.startsWith('#/checkout')||location.hash.startsWith('#/checkout?guest=1'))return;try{const cfg=await originalFetch('/api/config',{cache:'no-store'}).then(r=>r.json()),sb=supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true}}),session=(await sb.auth.getSession()).data.session;if(!session)return;const cart=JSON.parse(localStorage.getItem('nexora_cart')||'[]');if(!cart.length)return;const [pr,sr]=await Promise.all([sb.from('products').select('id,selling_price,stock,min_order_qty,delivery_charge,electrical_mrp,electrical_delivery_charge,product_variants(id,selling_price,stock,active)').eq('active',true).eq('approved_by_admin',true),sb.from('admin_settings').select('delivery_enabled,default_delivery_charge,electrical_delivery_charge,free_delivery_min_amount').limit(1).maybeSingle()]);if(pr.error||sr.error)return;const products=pr.data||[],settings=sr.data||{};const rows=cart.map(i=>{const p=products.find(x=>x.id===i.id),v=p?.product_variants?.find(x=>x.id===i.variant_id&&x.active!==false);return p?{...i,p,v,price:Number(v?.selling_price??p.selling_price??0)}:null}).filter(Boolean);const subtotal=rows.reduce((a,x)=>a+x.price*x.qty,0),qty=rows.reduce((a,x)=>a+x.qty,0);let shipping=0;if(settings.delivery_enabled!==false&&subtotal<Number(settings.free_delivery_min_amount||0))shipping=rows.reduce((a,x)=>{const e=x.p.electrical_mrp!=null,c=Number(e?x.p.electrical_delivery_charge||0:x.p.delivery_charge||0),f=Number(e?settings.electrical_delivery_charge||0:settings.default_delivery_charge||0);return a+(c>0?c:f)*x.qty},0);let discount=0;
const cards=[...document.querySelectorAll('.checkout-card')],paymentCard=cards.find(x=>/UPI payment/i.test(x.textContent||''));if(!paymentCard)return;const offer=document.createElement('div');offer.className='checkout-card';offer.innerHTML=`<h2>Offer code</h2><div class="row"><input id="offerCode" class="input" placeholder="Enter offer code" maxlength="64"><button class="btn secondary" id="applyOffer">Apply</button></div><div id="offerMsg"></div>`;paymentCard.parentNode.insertBefore(offer,paymentCard);
const update=(d=0)=>{discount=d;const total=Math.max(0,subtotal-discount+shipping);const summary=document.querySelector('.summary');if(summary){const totalEl=summary.querySelector('.total strong');if(totalEl)totalEl.textContent=money(total);let dis=summary.querySelector('#hotfixDiscount');if(dis)dis.remove();if(discount){dis=document.createElement('div');dis.id='hotfixDiscount';dis.innerHTML=`<span>Offer discount</span><b>−${money(discount)}</b>`;const hr=summary.querySelector('hr');if(hr)hr.before(dis)}}const links=[...document.querySelectorAll('.checkout-card a.btn')].filter(a=>String(a.getAttribute('href')||'').startsWith('upi://'));const upiAmount=total.toFixed(2);for(const a of links){const u=new URL(a.getAttribute('href'));u.searchParams.set('am',upiAmount);a.href=u.toString()}document.querySelectorAll('.upi-box img').forEach(img=>{const src=img.src;if(src.includes('api.qrserver.com')){const m=src.match(/[?&]data=([^&]+)/);if(m){const u=decodeURIComponent(m[1]);try{const x=new URL(u);x.searchParams.set('am',upiAmount);img.src=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(x.toString())}`}catch{}}}})};
update(0);document.getElementById('applyOffer').onclick=async()=>{const b=document.getElementById('applyOffer'),m=document.getElementById('offerMsg'),code=document.getElementById('offerCode').value.trim();if(!code){window.__nexoraOfferCode='';update(0);m.innerHTML='<div class="notice">Enter an offer code.</div>';return}b.disabled=true;try{const h={Authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},r=await originalFetch('/api/offer',{method:'POST',headers:h,body:JSON.stringify({code,subtotal,quantity:qty})}),d=await r.json();if(!r.ok||!d.valid)throw Error(d.error||'Offer is not valid');window.__nexoraOfferCode=d.code;update(Number(d.discount_amount||0));m.innerHTML=`<div class="notice success">${esc(d.code)} applied: ${money(d.discount_amount)} off.</div>`}catch(e){window.__nexoraOfferCode='';update(0);m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}finally{b.disabled=false}};
}catch{}}
window.addEventListener('hashchange',()=>setTimeout(setup,120));window.addEventListener('load',()=>setTimeout(setup,250));})();
