import {json,readBody,supabase,validAdmin,getSupabaseKey} from "./_utils.js";
export async function onRequestPost({request,env}){try{
 if(!(await validAdmin(request,env)))return json({error:"Admin login required"},401);if(!env.SUPABASE_URL||!getSupabaseKey(env))return json({error:"Server database configuration is incomplete"},500);const b=await readBody(request),a=String(b.action||"");
 if(a==="categories"){const r=await supabase(env,"categories?select=*&order=sort_order.asc,name.asc");const d=await r.json();return r.ok?json(d):json({error:"Unable to load categories",details:d},502)}
 if(a==="save_category"){const id=String(b.id||"").trim();const payload={name:String(b.name||"").trim(),slug:String(b.slug||"").trim().toLowerCase(),description:String(b.description||"").trim()||null,image_url:String(b.image_url||"").trim()||null,icon_url:String(b.icon_url||"").trim()||null,banner_url:String(b.banner_url||"").trim()||null,seo_title:String(b.seo_title||"").trim()||null,seo_description:String(b.seo_description||"").trim()||null,active:b.active!==false,sort_order:Number(b.sort_order||0),category_type:b.category_type||"OWN",source_name:String(b.source_name||"").trim()||null,source_category_id:String(b.source_category_id||"").trim()||null};if(!payload.name||!payload.slug)return json({error:"Category name and slug are required"},400);if(!payload.icon_url||!payload.banner_url)return json({error:"Favicon (icon) URL and Hero (banner) URL are required — 512×512 px (1:1) and 1600×600 px (8:3)"},400);const r=await supabase(env,id?`categories?id=eq.${encodeURIComponent(id)}`:"categories",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);return r.ok?json({ok:true,data:d}):json({error:"Category save failed",details:d},400)}
 if(a==="delete_category"){const r=await supabase(env,`categories?id=eq.${encodeURIComponent(String(b.id||""))}`,{method:"DELETE"});return r.ok?json({ok:true}):json({error:"Category delete failed",details:await r.text()},400)}
 if(a==="reviews"){const r=await supabase(env,"product_reviews?select=id,product_id,user_id,order_id,rating,title,body,verified_purchase,approved,created_at&order=created_at.desc");const d=await r.json();return r.ok?json(d):json({error:"Unable to load reviews",details:d},502)}
 if(a==="review_status"){const r=await supabase(env,`product_reviews?id=eq.${encodeURIComponent(String(b.id||""))}`,{method:"PATCH",body:JSON.stringify({approved:!!b.approved,updated_at:new Date().toISOString()})});return r.ok?json({ok:true}):json({error:"Review update failed",details:await r.text()},400)}
 if(a==="delete_review"){const r=await supabase(env,`product_reviews?id=eq.${encodeURIComponent(String(b.id||""))}`,{method:"DELETE"});return r.ok?json({ok:true}):json({error:"Review delete failed",details:await r.text()},400)}
 if(a==="support"){const r=await supabase(env,"support_tickets?select=*&order=created_at.desc");const d=await r.json();return r.ok?json(d):json({error:"Unable to load support tickets",details:d},502)}
 if(a==="support_status"){const status=String(b.status||"");if(!["open","in_progress","resolved","closed"].includes(status))return json({error:"Invalid support status"},400);const r=await supabase(env,`support_tickets?id=eq.${encodeURIComponent(String(b.id||""))}`,{method:"PATCH",body:JSON.stringify({status,updated_at:new Date().toISOString()})});return r.ok?json({ok:true}):json({error:"Support status update failed",details:await r.text()},400)}
 if(a==="settings"){const r=await supabase(env,"admin_settings?select=*&limit=1");const d=await r.json();return r.ok?json(d[0]||{}):json({error:"Unable to load settings",details:d},502)}
 if(a==="save_settings"){const allowed=['store_name','store_email','telegram_username','upi_id','currency','guest_checkout_enabled','user_registration_enabled','store_enabled','auto_product_import_enabled','auto_stock_sync_enabled','auto_publish_products','minimum_profit_amount','minimum_profit_percent','delivery_enabled','default_delivery_charge','electrical_delivery_charge','free_delivery_min_amount'];const payload={};for(const k of allowed)if(Object.prototype.hasOwnProperty.call(b,k))payload[k]=b[k];payload.updated_at=new Date().toISOString();const r=await supabase(env,"admin_settings?id=eq.true",{method:"PATCH",body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);return r.ok?json({ok:true,data:d}):json({error:"Settings save failed",details:d},400)}
 if(a==="user_status"){const r=await supabase(env,`profiles?id=eq.${encodeURIComponent(String(b.id||""))}`,{method:"PATCH",body:JSON.stringify({is_active:b.is_active!==false,is_blocked:!!b.is_blocked})});return r.ok?json({ok:true}):json({error:"User status update failed",details:await r.text()},400)}
 if(a==="variants"){const r=await supabase(env,`product_variants?product_id=eq.${encodeURIComponent(String(b.product_id||""))}&select=*&order=created_at.asc`);const d=await r.json();return r.ok?json(d):json({error:"Unable to load variants",details:d},502)}
 if(a==="save_variant"){const id=String(b.id||"").trim();const payload={product_id:String(b.product_id||"").trim(),variant_name:String(b.variant_name||"").trim(),sku:String(b.sku||"").trim()||null,attributes:b.attributes||{},cost_price:Number(b.cost_price||0),selling_price:Number(b.selling_price||0),stock:Math.max(0,Math.floor(Number(b.stock||0))),active:b.active!==false,updated_at:new Date().toISOString()};if(!payload.product_id||!payload.variant_name||payload.selling_price<0)return json({error:"Valid product, variant name and price are required"},400);const r=await supabase(env,id?`product_variants?id=eq.${encodeURIComponent(id)}`:"product_variants",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);return r.ok?json({ok:true,data:d}):json({error:"Variant save failed",details:d},400)}
 if(a==="delete_variant"){const r=await supabase(env,`product_variants?id=eq.${encodeURIComponent(String(b.id||""))}`,{method:"DELETE"});return r.ok?json({ok:true}):json({error:"Variant delete failed",details:await r.text()},400)}
 if(a==="shipping_orders"){const r=await supabase(env,"supplier_orders?select=id,order_id,supplier_order_number,status,tracking_number,tracking_url,carrier,tracking_status,ordered_at,shipped_at,delivered_at,last_submission_error,next_retry_at&order=created_at.desc");const d=await r.json();return r.ok?json(d):json({error:"Unable to load shipping orders",details:d},502)}
 return json({error:"Unknown admin-ops action"},400);
}catch(e){return json({error:"Admin operation failed",details:String(e?.message||e)},500)}}