const CJ_BASE="https://developers.cjdropshipping.com/api2.0/v1";
const GROUPS=[
 {key:"footwear",name:"Footwear",keywords:["footwear","shoes","sneakers"],match:/\b(shoe|footwear|sneaker|sandal|slipper|boot|loafer|heel|flat|running shoe)\b/i},
 {key:"kitchen",name:"Kitchen Appliances",keywords:["kitchen appliance","kitchen","home appliance"],match:/\b(kitchen|appliance|blender|mixer|juicer|chopper|air fryer|kettle|toaster|sandwich maker|rice cooker|coffee maker|food processor|induction|electric cooker)\b/i},
 {key:"clothes",name:"Clothes",keywords:["clothing","clothes","apparel","fashion"],match:/\b(clothing|clothes|apparel|shirt|t-shirt|tshirt|top|dress|jeans|trouser|pant|kurti|saree|hoodie|jacket|shorts|skirt|wear|fashion)\b/i},
 {key:"fitness",name:"Fitness",keywords:["fitness","sports","gym","workout"],match:/\b(fitness|gym|exercise|workout|sports|yoga|training|resistance|dumbbell|skipping)\b/i},
 {key:"pet",name:"Pet",keywords:["pet supplies","pet","dog","cat"],match:/\b(pet|dog|cat|puppy|kitten|leash|collar|grooming|kennel|aquarium)\b/i}
];
function textOf(p){return [p.nameEn,p.productNameEn,p.productName,p.name,p.threeCategoryName,p.twoCategoryName,p.oneCategoryName,p.categoryName].filter(Boolean).join(" ").toLowerCase()}
function money(v){const m=String(v??"").replace(/,/g,"").match(/\d+(?:\.\d+)?/);return m?Number(m[0]):0}
function popularity(p,i=0){const raw=JSON.stringify(p).toLowerCase();let s=1000-i;if(/best.?seller|top.?seller|popular|hot|trending|top.?pick|recommended|sales/.test(raw))s+=1500;for(const k of ["salesCount","saleCount","soldCount","orders","orderCount","sold","sales"]){const n=Number(p?.[k]||0);if(Number.isFinite(n)&&n>0)s+=Math.min(2000,Math.log10(n+1)*400)}return s}
async function getToken(env){const k=String(env.CJ_API_KEY||"").trim(),a=String(env.CJ_ACCESS_TOKEN||"").trim(),f=String(env.CJ_REFRESH_TOKEN||"").trim();if(k){const r=await fetch(`${CJ_BASE}/authentication/getAccessToken`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey:k})});const d=await r.json().catch(()=>({}));if(r.ok&&d.code===200&&d.data?.accessToken)return d.data.accessToken;if(!a&&!f)throw Error(`CJ authentication failed (${d.code||r.status}): ${d.message||""}`)}if(f){const r=await fetch(`${CJ_BASE}/authentication/refreshAccessToken`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refreshToken:f})});const d=await r.json().catch(()=>({}));if(r.ok&&d.code===200&&d.data?.accessToken)return d.data.accessToken}if(a)return a;throw Error("CJ credentials are missing.")}
async function search(t,k){const u=new URL(`${CJ_BASE}/product/listV2`);u.searchParams.set("page","1");u.searchParams.set("size","100");u.searchParams.set("keyWord",k);u.searchParams.set("features","enable_category");const r=await fetch(u,{headers:{"CJ-Access-Token":t}});const d=await r.json().catch(()=>({}));if(!r.ok||d.code!==200)throw Error(`CJ product query failed for ${k} (${d.code||r.status})`);return(d.data?.content||[]).flatMap(x=>x.productList||[])}
async function inventory(t,id){const u=new URL(`${CJ_BASE}/product/stock/getInventoryByPid`);u.searchParams.set("pid",id);const r=await fetch(u,{headers:{"CJ-Access-Token":t}});const d=await r.json().catch(()=>({}));if(!r.ok||d.code!==200)return null;const a=(d.data?.inventories||[]).map(x=>Number(x.totalInventoryNum)).filter(Number.isFinite);if(a.length)return Math.max(...a);const b=(d.data?.variantInventories||[]).flatMap(v=>v.inventory||[]).map(x=>Number(x.totalInventory)).filter(Number.isFinite);return b.length?Math.max(...b):null}
function catId(cs,g){const aliases={footwear:["footwear","shoes","footwear products"],kitchen:["kitchen appliances","kitchen appliance","kitchen & home appliances"],clothes:["clothes","clothing","apparel"],fitness:["fitness","sports & fitness","sports and fitness"],pet:["pet","pet supplies","pet supplies & accessories"]}[g];return cs.find(c=>aliases.includes(String(c.name||"").trim().toLowerCase()))?.id||null}
async function upsert(env,supabase,rows){if(!rows.length)return;const r=await supabase(env,"products?on_conflict=source,source_product_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows)});if(!r.ok)throw Error(`Supabase CJ batch upsert failed (${r.status}): ${await r.text()}`)}
export async function syncCJRobust(env,supabase,index){const g=GROUPS[index];if(!g)throw Error("Invalid CJ category index");const cr=await supabase(env,"categories?select=id,name,slug&active=eq.true"),cs=await cr.json();if(!Array.isArray(cs))throw Error("Could not load store categories");const cid=catId(cs,g.key);if(!cid)throw Error(`CJ category mapping missing for ${g.key}`);const t=await getToken(env),seen=new Map(),warnings=[];for(const k of g.keywords){try{for(const p of await search(t,k)){const id=String(p.id||p.productId||"");if(!id)continue;const txt=textOf(p);if(!g.match.test(txt))continue;const score=popularity(p);const old=seen.get(id);if(!old||score>old.s)seen.set(id,{p,s:score})}}catch(e){warnings.push(`${k}: ${e.message}`)}}const exr=await supabase(env,"products?select=source_product_id,selling_price,active,approved_by_admin&source=eq.CJ"),ex=await exr.json();if(!exr.ok||!Array.isArray(ex))throw Error("Could not load existing CJ products");const em=new Map(ex.map(x=>[String(x.source_product_id),x]));const autoR=await supabase(env,"admin_settings?select=auto_publish_products&limit=1"),ad=await autoR.json().catch(()=>[]),auto=autoR.ok&&ad?.[0]?.auto_publish_products===true,rate=Number(env.CJ_USD_INR_RATE||0)>0?Number(env.CJ_USD_INR_RATE):90,rows=[];for(const {p} of [...seen.values()].sort((a,b)=>b.s-a.s).slice(0,Math.max(1,Math.min(100,Number(env.CJ_SYNC_MAX_PER_CATEGORY)||20)))){const id=String(p.id||p.productId),old=em.get(id),usd=[p.nowPrice,p.discountPrice,p.sellPrice,p.price].map(money).find(n=>n>0)||0;let stock=Math.max(0,Number(p.warehouseInventoryNum||p.totalVerifiedInventory||0)||0);if(stock<=0)stock=await inventory(t,id);if(!(stock>0))continue;const cost=Number((usd*rate).toFixed(2));const row={name:p.nameEn||p.productNameEn||p.productName||p.name||"CJ Product",source:"CJ",source_product_id:id,source_sku:p.sku||p.spu||null,category_id:cid,image_url:p.bigImage||p.productImage||p.imageUrl||null,cost_price:cost,suggested_price:Number((cost*1.5).toFixed(2)),selling_price:Number((cost*1.5).toFixed(2)),stock,stock_mode:"AUTO",last_stock_sync_at:new Date().toISOString()};if(!old){row.active=auto;row.approved_by_admin=auto;if(auto)row.approved_at=new Date().toISOString()}else if(Number(old.selling_price||0)>0){delete row.suggested_price;delete row.selling_price}rows.push(row)}await upsert(env,supabase,rows);return{key:g.key,name:g.name,imported:rows.length,warnings}}
