const CJ_BASE="https://developers.cjdropshipping.com/api2.0/v1";
const CURSOR_STEP=100000;
async function usdInrRate(env){const o=Number(env.CJ_USD_INR_RATE||0);if(o>0)return o;try{const r=await fetch("https://open.er-api.com/v6/latest/USD");const d=await r.json().catch(()=>null);const v=Number(d?.rates?.INR);if(r.ok&&v>0)return v}catch{}return 90}
async function requestTokenFromApiKey(k){const r=await fetch(`${CJ_BASE}/authentication/getAccessToken`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey:k})});const d=await r.json().catch(()=>({}));if(r.ok&&d.code===200&&d.data?.accessToken)return d.data.accessToken;const e=new Error(`CJ API-key authentication failed (${d.code||r.status}): ${String(d.message||JSON.stringify(d))}`);e.cjCode=d.code;throw e}
async function logoutToken(t){if(!t)return;try{await fetch(`${CJ_BASE}/authentication/logout`,{method:"POST",headers:{"CJ-Access-Token":t}})}catch{}}
async function refreshToken(t){const r=await fetch(`${CJ_BASE}/authentication/refreshAccessToken`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refreshToken:t})});const d=await r.json().catch(()=>({}));return r.ok&&d.code===200&&d.data?.accessToken?d.data.accessToken:null}
async function getAccessToken(env){const k=String(env.CJ_API_KEY||"").trim(),a=String(env.CJ_ACCESS_TOKEN||"").trim(),f=String(env.CJ_REFRESH_TOKEN||"").trim();if(k){try{return await requestTokenFromApiKey(k)}catch(e){if(!a&&!f)throw e}}if(f){const t=await refreshToken(f);if(t)return t}if(a)return a;throw new Error("CJ credentials are missing.")}
function textOf(p){return [p.nameEn,p.threeCategoryName,p.twoCategoryName,p.oneCategoryName].filter(Boolean).join(" ").toLowerCase()}
const GROUPS={
 footwear:{aliases:["Footwear","Shoes","Footwear Products"],keyword:"footwear",match:/\b(shoe|footwear|sneaker|sandal|slipper|boot|loafer|heel|flat|running shoe)\b/i},
 kitchen:{aliases:["Kitchen Appliances","Kitchen appliance","Kitchen & Home Appliances"],keyword:"kitchen appliance",match:/\b(kitchen|appliance|blender|mixer|juicer|chopper|air fryer|kettle|toaster|sandwich maker|rice cooker|coffee maker|food processor|induction|electric cooker)\b/i},
 clothes:{aliases:["Clothes","Clothing","Apparel"],keyword:"clothing",match:/\b(clothing|clothes|apparel|shirt|t-shirt|tshirt|top|dress|jeans|trouser|pant|kurti|saree|hoodie|jacket|shorts|skirt|wear)\b/i},
 fitness:{aliases:["Fitness","Sports & Fitness","Sports and Fitness"],keyword:"fitness",match:/\b(fitness|gym|exercise|workout|sports|yoga|training|resistance|dumbbell|skipping)\b/i},
 pet:{aliases:["Pet","Pet Supplies","Pet Supplies & Accessories"],keyword:"pet",match:/\b(pet|dog|cat|puppy|kitten|leash|collar|grooming|kennel|aquarium)\b/i}
};
function catId(cs,a){const w=a.map(x=>x.toLowerCase());return cs.find(c=>w.includes(String(c.name||"").trim().toLowerCase()))?.id||null}
function slugId(cs,s){return cs.find(c=>String(c.slug||"").toLowerCase()===s)?.id||null}
function categoryForProduct(cs,g,t){const main=catId(cs,GROUPS[g].aliases);if(g==="footwear"||g==="clothes"){const b=g;if(/\b(kid|kids|child|children)\b/i.test(t)){const x=slugId(cs,`${b}-kids`);if(x)return x}if(/\b(women|woman|ladies|female)\b/i.test(t)){const x=slugId(cs,`${b}-women`);if(x)return x}if(/\b(men|man|male)\b/i.test(t)){const x=slugId(cs,`${b}-men`);if(x)return x}}return main}
function parseMoney(v){const m=String(v??"").replace(/,/g,"").match(/\d+(?:\.\d+)?/);return m?Number(m[0]):0}
function popularity(p,i){const raw=JSON.stringify(p).toLowerCase();let s=500-i;if(/best.?seller|top.?seller|popular|hot|trending|top.?pick|recommended/.test(raw))s+=1000;for(const k of ["salesCount","saleCount","soldCount","orders","orderCount","sold","sales"]){const n=Number(p?.[k]||0);if(Number.isFinite(n)&&n>0)s+=Math.min(1000,Math.log10(n+1)*250)}return s}
async function searchProducts(t,k,page=1,size=100){const u=new URL(`${CJ_BASE}/product/listV2`);u.searchParams.set("page",String(page));u.searchParams.set("size",String(size));u.searchParams.set("keyWord",k);u.searchParams.set("features","enable_category");const r=await fetch(u,{headers:{"CJ-Access-Token":t}});const d=await r.json().catch(()=>({}));if(!r.ok||d.code!==200){const e=new Error(`CJ product query failed for ${k} (${d.code||r.status})`);e.cjCode=d.code;throw e}return(d.data?.content||[]).flatMap(x=>x.productList||[])}
async function inventoryByProductId(t,pid){const u=new URL(`${CJ_BASE}/product/stock/getInventoryByPid`);u.searchParams.set("pid",String(pid));const r=await fetch(u,{headers:{"CJ-Access-Token":t}});const d=await r.json().catch(()=>({}));if(!r.ok||d.code!==200)return null;const a=(d.data?.inventories||[]).map(x=>Number(x.totalInventoryNum)).filter(Number.isFinite).filter(n=>n>=0);if(a.length)return Math.max(...a);const b=(d.data?.variantInventories||[]).flatMap(v=>v.inventory||[]).map(x=>Number(x.totalInventory)).filter(Number.isFinite).filter(n=>n>=0);return b.length?Math.max(...b):null}
async function upsertBatch(env,supabase,rows){if(!rows.length)return;const gs=new Map();for(const r of rows){const s=Object.keys(r).sort().join(" ");if(!gs.has(s))gs.set(s,[]);gs.get(s).push(r)}for(const g of gs.values()){const r=await supabase(env,"products?on_conflict=source,source_product_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(g)});if(!r.ok)throw new Error(`Supabase CJ batch upsert failed (${r.status}): ${await r.text()}`)}}
async function existing(env,supabase){const r=await supabase(env,"products?select=source_product_id,selling_price,active,approved_by_admin&source=eq.CJ");const d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error("Could not load existing CJ products");const m=new Map();for(const x of d)m.set(String(x.source_product_id),{sell:Number(x.selling_price||0)||0,active:x.active===true,approved:x.approved_by_admin===true});return m}
function parseCursor(v){const n=Number(v||0);return Number.isFinite(n)&&n>=0?{i:Math.floor(n/CURSOR_STEP)}:{i:0}}
export async function syncCJ(env,supabase,opts={}){
 const max=Math.max(1,Math.min(100,Number(env.CJ_SYNC_MAX_PER_CATEGORY)||20)),names=Object.keys(GROUPS),start=parseCursor(opts.cursor),warnings=[],rows=[];let token=await getAccessToken(env);const cr=await supabase(env,"categories?select=id,name,slug&active=eq.true"),cs=await cr.json();if(!Array.isArray(cs))throw new Error("Could not load store categories");for(const g of names)if(!categoryForProduct(cs,g,""))throw new Error(`CJ category mapping missing for ${g}`);const ex=await existing(env,supabase);let auto=false;try{const r=await supabase(env,"admin_settings?select=auto_publish_products&limit=1"),d=await r.json();auto=r.ok&&d?.[0]?.auto_publish_products===true}catch{}const rate=await usdInrRate(env);let i=start.i;for(;i<names.length;i++){const g=names[i],spec=GROUPS[g],seen=new Set(),cand=[];let ps=[];try{ps=await searchProducts(token,spec.keyword,1,100)}catch(e){if(Number(e?.cjCode)===1600001&&env.CJ_API_KEY){try{await logoutToken(token);token=await requestTokenFromApiKey(String(env.CJ_API_KEY).trim());ps=await searchProducts(token,spec.keyword,1,100)}catch(e2){warnings.push(`${g}: ${String(e2?.message||e2)}`);continue}}else{warnings.push(`${g}: ${String(e?.message||e)}`);continue}}ps.forEach((p,n)=>{const id=String(p.id||p.productId||"");if(!id||seen.has(id)||!spec.match.test(textOf(p)))return;seen.add(id);cand.push({p,s:popularity(p,n)})});cand.sort((a,b)=>b.s-a.s);for(const {p} of cand.slice(0,max)){const id=String(p.id||p.productId),t=textOf(p),cid=categoryForProduct(cs,g,t),usd=[p.nowPrice,p.discountPrice,p.sellPrice].map(parseMoney).find(n=>n>0)||0,cost=Number((usd*rate).toFixed(2)),listStock=Math.max(0,Number(p.warehouseInventoryNum||p.totalVerifiedInventory||0)||0),old=ex.get(id),isNew=!old,payload={name:p.nameEn||"CJ Product",source:"CJ",source_product_id:id,source_sku:p.sku||p.spu||null,category_id:cid,image_url:p.bigImage||p.productImage||p.imageUrl||null,cost_price:cost,suggested_price:Number((cost*1.5).toFixed(2)),selling_price:Number((cost*1.5).toFixed(2)),stock:listStock,stock_mode:"AUTO",last_stock_sync_at:new Date().toISOString()};if(isNew){payload.active=auto;payload.approved_by_admin=auto;if(auto)payload.approved_at=new Date().toISOString()}else if(old.sell>0){delete payload.suggested_price;delete payload.selling_price}let stock=listStock>0?listStock:null;if(stock===null)stock=await inventoryByProductId(token,id);if(stock===null||stock<=0){if(isNew)continue;payload.stock=0;if(old.active)payload.active=false}else{payload.stock=stock;if(!isNew&&!old.active&&old.approved)payload.active=true}rows.push(payload)}}if(i<names.length-1)break}
 await upsertBatch(env,supabase,rows);const counts={footwear:0,kitchen:0,clothes:0,fitness:0,pet:0};for(const r of rows){for(const g of names){if(r.category_id===categoryForProduct(cs,g,"")){counts[g]++;break}}}const done=i>=names.length-1;return {...counts,imported:rows.length,done,cursor:done?null:(i+1)*CURSOR_STEP,warnings,errors:warnings,auto_publish:auto}
}
