const DEODAP_BASE="https://deodap.in";
const CURSOR_STEP=100000;
const GROUPS={
 jewellery:{aliases:["Artificial Jewellery","Artificial Jewelry","Jewellery","Jewelry"],collections:["jewellery","jewellery-accessories","womens-jewellery","mens-jewellery"]},
 daily:{aliases:["Daily Use Products","Daily Use","Daily Use Items","Daily Essentials"],collections:["kitchen-home-appliances","cleaning-housekeeping","household-supplies","office-supplies","stationery-school-supplies","health-care","home-utilities-safety"]},
 car:{aliases:["Car Accessories","Automotive"],collections:["car-accessories","car-accessories-fashion","automotive","car-accessories-general"]},
 electrical:{aliases:["Electrical","Electrical Appliances","Electrical & Power"],collections:["electrical-supplies","electrical-power-supplies"]},
 mobile:{aliases:["Mobile Accessories","Mobiles & Accessories","Mobiles & Accessories Fashion"],collections:["mobile-accessories","mobiles-accessories-fashion"]}
};
function stripHtml(v){return String(v||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,5000)}
function moneyNumber(v){const n=Number(String(v??"").replace(/[^0-9.\-]/g,""));return Number.isFinite(n)?n:0}
function imageUrl(p){const raw=p.images?.[0]?.src||p.featured_image?.src||p.variants?.[0]?.featured_image?.src||null;if(!raw)return null;return String(raw).startsWith("//")?`https:${raw}`:String(raw)}
async function fetchCollection(h){const u=`${DEODAP_BASE}/collections/${encodeURIComponent(h)}/products.json?limit=250`;const r=await fetch(u,{headers:{Accept:"application/json","User-Agent":"Nexora-India/1.0"}});const d=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(d.products))throw new Error(`collection '${h}' unavailable (${r.status})`);return d.products}
function findCategory(cs,a){const w=a.map(x=>x.toLowerCase());return cs.find(c=>w.includes(String(c.name||"").trim().toLowerCase()))?.id||null}
function availability(p){const vs=Array.isArray(p.variants)?p.variants:[],q=vs.map(v=>Number(v.inventory_quantity)).filter(Number.isFinite).filter(n=>n>=0);if(q.length)return{available:q.some(n=>n>0),stock:Math.max(...q),authoritative:true};const f=vs.map(v=>v.available).filter(v=>typeof v==="boolean");if(f.length)return{available:f.some(Boolean),stock:0,authoritative:false};return{available:typeof p.available==="boolean"?p.available:null,stock:0,authoritative:false}}
function popularity(p,i){const raw=JSON.stringify(p).toLowerCase();let s=500-i;if(/best.?seller|top.?grab|top.?seller|popular|trending|customer.?favorite|deo.?dap.?pick|mega.?saving/.test(raw))s+=1000;for(const k of ["salesCount","saleCount","soldCount","orders","orderCount","reviewCount"]){const n=Number(p?.[k]||0);if(Number.isFinite(n)&&n>0)s+=Math.min(1500,Math.log10(n+1)*350)}return s}
function build(p,cid,ex,opts){const v=p.variants?.[0]||{},price=moneyNumber(v.price||p.price||0),suggested=Number((price*1.5).toFixed(2)),a=availability(p);if(a.available===true&&!a.authoritative)a.stock=Math.max(1,Number(opts.untrackedStock||25));if(a.available!==true){if(ex===undefined)return null;const o={name:p.title||"DeoDap Product",source:"DEODAP",source_product_id:String(p.id),stock:0,stock_mode:"AUTO",last_stock_sync_at:new Date().toISOString()};if(ex.active)o.active=false;return o}const row={name:p.title||"DeoDap Product",slug:p.handle||null,description:stripHtml(p.body_html),source:"DEODAP",source_product_id:String(p.id),source_sku:v.sku||null,category_id:cid,image_url:imageUrl(p),cost_price:price,suggested_price:suggested,selling_price:suggested,stock:a.stock,stock_mode:"AUTO",last_stock_sync_at:new Date().toISOString()};if(ex===undefined){row.active=opts.publish===true;row.approved_by_admin=opts.publish===true;if(opts.publish===true)row.approved_at=new Date().toISOString();if(Number(opts.deliveryCharge)>0)row.delivery_charge=Number(opts.deliveryCharge)}else if(Number(ex.sell)>0){delete row.suggested_price;delete row.selling_price}if(ex!==undefined&&!ex.active&&ex.approved)row.active=true;return row}
async function upsertBatch(env,supabase,rows){if(!rows.length)return;const gs=new Map();for(const r of rows){const s=Object.keys(r).sort().join(" ");if(!gs.has(s))gs.set(s,[]);gs.get(s).push(r)}for(const g of gs.values()){const r=await supabase(env,"products?on_conflict=source,source_product_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(g)});if(!r.ok)throw new Error(`Supabase DeoDap batch upsert failed (${r.status}): ${await r.text()}`)}}
async function existing(env,supabase){const r=await supabase(env,"products?select=source_product_id,selling_price,active,approved_by_admin&source=eq.DEODAP"),d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error("Could not load existing DeoDap products");const m=new Map();for(const x of d)m.set(String(x.source_product_id),{sell:Number(x.selling_price||0)||0,active:x.active===true,approved:x.approved_by_admin===true});return m}
export async function syncDeodap(env,supabase,opts={}){
 const max=Math.max(1,Math.min(100,Number(env.DEODAP_MAX_PER_CATEGORY)||20)),cr=await supabase(env,"categories?select=id,name,slug&active=eq.true"),cs=await cr.json();if(!Array.isArray(cs))throw new Error("Could not load store categories");const ex=await existing(env,supabase);let auto=false;try{const r=await supabase(env,"admin_settings?select=auto_publish_products&limit=1"),d=await r.json();auto=r.ok&&d?.[0]?.auto_publish_products===true}catch{}const opts2={publish:auto,deliveryCharge:String(env.DEODAP_DELIVERY_CHARGE??"").trim()===""?199:Number(env.DEODAP_DELIVERY_CHARGE)||0,untrackedStock:Math.max(1,Number(env.DEODAP_DEFAULT_STOCK||25)||25)},warnings=[],rows=[],names=Object.keys(GROUPS);const start=Math.max(0,Math.floor(Number(opts.cursor||0)/CURSOR_STEP));
 if(start>=names.length)return{jewellery:0,daily:0,car:0,electrical:0,mobile:0,imported:0,auto_publish:auto,done:true,cursor:null,warnings,errors:warnings};
 const g=names[start],cid=findCategory(cs,GROUPS[g].aliases);if(!cid)throw new Error(`DeoDap category mapping missing for ${g}`);const seen=new Set(),cand=[];for(const h of GROUPS[g].collections){let ps=[];try{ps=await fetchCollection(h)}catch(e){warnings.push(`${g}/${h}: ${String(e?.message||e)}`);continue}ps.forEach((p,i)=>{const id=String(p.id||"");if(!id||seen.has(id))return;seen.add(id);cand.push({p,s:popularity(p,i)})})}cand.sort((a,b)=>b.s-a.s);for(const x of cand.slice(0,max)){const r=build(x.p,cid,ex.get(String(x.p.id)),opts2);if(r)rows.push(r)}await upsertBatch(env,supabase,rows);const counts={jewellery:0,daily:0,car:0,electrical:0,mobile:0};counts[g]=rows.length;const done=start>=names.length-1;return{...counts,imported:rows.length,skipped_no_stock:0,auto_publish:auto,done,cursor:done?null:(start+1)*CURSOR_STEP,warnings,errors:warnings}
}
